### ISSUE TITLE
Add more owners on npm

### ISSUE THREAD

**Issue by TimothyGu** [jstransformers/jstransformer-mustache#2]
CC @RobLoach 

Please add me and the rest of @jstransformers as owners on npm.

**Comment by TimothyGu** [comment]
@RobLoach I also added an annotated tag on 0.0.2 release, so if you get a chance you can just publish it.

**Comment by RobLoach** [comment]
:+1:

**Comment by TimothyGu** [comment]
Thanks

**Comment by hemanth** [comment]
:+1:
